[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[server]
enableStaticServing = true
runOnSave = true
maxUploadSize = 200
maxMessageSize = 200
enableCORS = true
enableXsrfProtection = true

[mapbox]
token = ""

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false
